// Generated by AgentSync from Codex/Claude/Cursor hook config.
// OpenCode auto-loads local plugins from .opencode/plugins/.
import { spawn } from "node:child_process";

const AGENTSYNC_HOOKS = [
  {
    "command": "bash \"$(git rev-parse --show-toplevel)/.codex/hooks/run-tests-for-edited-file.sh\"",
    "event": "tool.execute.after",
    "location": "hook.PostToolUse[0].hooks[0]",
    "timeoutSeconds": 120,
    "tools": [
      "edit",
      "write",
      "apply_patch"
    ]
  },
  {
    "command": "bash \"$(git rev-parse --show-toplevel)/.codex/hooks/enforce-patch-paths.sh\"",
    "event": "tool.execute.before",
    "location": "hook.PreToolUse[0].hooks[0]",
    "timeoutSeconds": 10,
    "tools": [
      "edit",
      "write",
      "apply_patch"
    ]
  },
  {
    "command": "bash \"$(git rev-parse --show-toplevel)/.codex/hooks/enforce-validation-subagents.sh\"",
    "event": "tool.execute.before",
    "location": "hook.PreToolUse[1].hooks[0]",
    "timeoutSeconds": 10,
    "tools": [
      "bash"
    ]
  }
];

export const AgentSyncHooks = async (context = {}) => {
  const cwd = context.directory ?? process.cwd();
  return {
    "tool.execute.before": async (input, output) => {
      await runAgentSyncHooks("tool.execute.before", { input, output }, input?.tool, cwd);
    },
    "tool.execute.after": async (input, output) => {
      await runAgentSyncHooks("tool.execute.after", { input, output }, input?.tool, cwd);
    },
    "permission.ask": async (input, output) => {
      await runAgentSyncHooks("permission.ask", { input, output }, undefined, cwd);
    },
    "experimental.session.compacting": async (input, output) => {
      await runAgentSyncHooks("experimental.session.compacting", { input, output }, undefined, cwd);
    },
    event: async (input) => {
      await runAgentSyncHooks(input?.event?.type, input, undefined, cwd);
    },
  };
};

async function runAgentSyncHooks(eventName, payload, toolName, cwd) {
  if (!eventName) return;
  for (const entry of AGENTSYNC_HOOKS) {
    if (entry.event !== eventName) continue;
    if (entry.tools?.length) {
      if (!toolName || !entry.tools.includes(toolName)) continue;
    }
    await runCommand(entry, buildHookPayload(eventName, payload, toolName), cwd);
  }
}

function buildHookPayload(eventName, payload, toolName) {
  const input = payload?.input ?? {};
  const output = payload?.output ?? {};
  const event = payload?.event ?? {};
  return {
    hook_event_name: eventName,
    session_id: input.sessionID ?? event.properties?.sessionID ?? event.properties?.session?.id,
    call_id: input.callID,
    tool_name: toolName ?? input.tool,
    tool_input: output.args ?? input.args,
    tool_output: output.output,
    permission: input,
    opencode: payload,
  };
}

async function runCommand(entry, payload, cwd) {
  return await new Promise((resolve, reject) => {
    const child = spawn(entry.command, {
      cwd,
      env: process.env,
      shell: true,
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    let timedOut = false;
    const timer = Number.isInteger(entry.timeoutSeconds)
      ? setTimeout(() => {
          timedOut = true;
          child.kill("SIGTERM");
        }, entry.timeoutSeconds * 1000)
      : undefined;

    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    child.on("error", (error) => {
      if (timer) clearTimeout(timer);
      reject(error);
    });
    child.on("close", (code) => {
      if (timer) clearTimeout(timer);
      if (timedOut) {
        reject(new Error(`AgentSync hook ${entry.location} timed out after ${entry.timeoutSeconds}s`));
        return;
      }
      if (code !== 0) {
        reject(new Error(stderr.trim() || stdout.trim() || `AgentSync hook ${entry.location} exited with code ${code}`));
        return;
      }
      try {
        applyHookDecision(entry, stdout, payload);
      } catch (error) {
        reject(error);
        return;
      }
      resolve();
    });
    child.stdin.end(JSON.stringify(payload));
  });
}

function applyHookDecision(entry, stdout, payload) {
  const text = stdout.trim();
  if (!text) return;
  let message;
  try {
    message = JSON.parse(text);
  } catch {
    return;
  }
  const decision = message?.decision ?? (message?.block === true ? "block" : undefined);
  if (entry.event === "permission.ask" && payload?.opencode?.output) {
    if (decision === "block" || decision === "deny") {
      payload.opencode.output.status = "deny";
      return;
    }
    if (decision === "allow" || decision === "approve") {
      payload.opencode.output.status = "allow";
      return;
    }
  }
  if (decision === "block" || decision === "deny") {
    throw new Error(message.reason || message.message || `AgentSync hook ${entry.location} blocked execution`);
  }
}
