"""Provider contracts and adapters."""

from __future__ import annotations

from bragi.providers.contracts import (
    ChatMessage,
    ChatReasoningConfig,
    ChatRequest,
    ChatResponse,
    ImageDescriptionRequest,
    ImageDescriptionResponse,
    ImageRequest,
    ImageResponse,
    ProviderCapability,
    ProviderClient,
    ProviderConfigStatus,
    ProviderModel,
    ProviderModelListResponse,
    ProviderModelPricing,
    ProviderRetryProgress,
    ProviderRetryProgressCallback,
    ProviderThinkingLevelSupport,
    ProviderToolCall,
    StructuredOutputProvider,
    StructuredOutputRequest,
    StructuredOutputResponse,
    ToolCallMessage,
    ToolCallProvider,
    ToolCallRequest,
    ToolCallResponse,
    ToolDefinition,
    VideoProvider,
    VideoRequest,
    VideoResponse,
    VisionProvider,
)
from bragi.providers.errors import ProviderError, ProviderErrorCategory
from bragi.providers.fake import FakeProviderClient
from bragi.providers.openrouter import OpenRouterClient
from bragi.providers.venice import VeniceClient

__all__ = [
    "ChatMessage",
    "ChatReasoningConfig",
    "ChatRequest",
    "ChatResponse",
    "ImageDescriptionRequest",
    "ImageDescriptionResponse",
    "ImageRequest",
    "ImageResponse",
    "ProviderCapability",
    "ProviderClient",
    "ProviderConfigStatus",
    "ProviderError",
    "ProviderErrorCategory",
    "ProviderModel",
    "ProviderModelListResponse",
    "ProviderModelPricing",
    "ProviderRetryProgress",
    "ProviderRetryProgressCallback",
    "ProviderThinkingLevelSupport",
    "ProviderToolCall",
    "StructuredOutputProvider",
    "StructuredOutputRequest",
    "StructuredOutputResponse",
    "ToolCallMessage",
    "ToolCallProvider",
    "ToolCallRequest",
    "ToolCallResponse",
    "ToolDefinition",
    "VideoProvider",
    "VideoRequest",
    "VideoResponse",
    "VisionProvider",
    "FakeProviderClient",
    "OpenRouterClient",
    "VeniceClient",
]
